# Generated by Django 4.0.4 on 2022-06-17 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.usertype'),
        ),
    ]
