# Generated by Django 4.0.5 on 2022-06-20 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_create_date_alter_comment_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='create_end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 25, 16, 32, 43, 737109), verbose_name='노출 종료'),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='노출 시작'),
        ),
    ]
