# Generated by Django 4.0.5 on 2022-06-21 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_article_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 15, 35, 2, 630538), verbose_name='노출 시작'),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 28, 15, 35, 2, 630538), verbose_name='노출 종료'),
        ),
    ]
